LogFile /var/spamtagger/log/clamav/clamspamd.log
PidFile /var/spamtagger/run/clamav/clamspamd.pid
TemporaryDirectory /var/spamtagger/spool/tmp
DatabaseDirectory /var/spamtagger/spool/clamspam
LocalSocket /var/spamtagger/run/clamav/clamspamd.sock

LogFileMaxSize 200M
LogTime yes

FixStaleSocket 1

MaxDirectoryRecursion 10

SelfCheck 1800

User clamav

ScanPE yes
ScanOLE2 yes
ScanMail yes
ScanHTML yes
ScanArchive yes
PhishingScanURLs yes
HeuristicAlerts yes
