[DEFAULT]
db_url = sqlite:////var/spamtagger/spool/fangfrisch/db.sqlite

local_directory = /var/spamtagger/spool/clamav
max_size = 25MB
on_update_exec = clamdscan --reload
on_update_timeout = 42

[interserver]
enabled = yes

[urlhaus]
enabled = yes
max_size = 2MB
