#!/bin/sh
#/etc/init.d/commtouch: start Commtouch daemons.

export PATH=$PATH:/sbin:/usr/sbin

COMMTOUCH_BASEDIR=/opt/commtouch
CTASD_STARTER=$COMMTOUCH_BASEDIR/etc/init.d/ctasd_initd
CTIPD_STARTER=$COMMTOUCH_BASEDIR/etc/init.d/ctipd.init_d

if [ ! -f $CTASD_STARTER ]; then
  echo "ctasd daemon not installed."
  exit 1
fi
if [ ! -f $CTIPD_STARTER ]; then
  echo "ctipd daemon not installed."
  exit 1
fi

prepare() {
  PREFILTER_CT=$(grep 'Pre Filters' /var/spamtagger/tmp/configs/mailscanner/MailScanner.conf | grep 'Commtouch')
  if [ "$PREFILTER_CT" = "" ]; then
    echo "Commtouch module not enabled"
    exit 0
  fi
}

case "$1" in
start)
  touch /var/spamtagger/run/commtouch.start.rs
  echo "  Starting Commtouch daemons: "
  prepare
  echo -n "    Ctasd daemon..."
  $CTASD_STARTER start >/dev/null
  echo " started."
  echo -n "    Ctipd daemon..."
  $CTIPD_STARTER start >/dev/null
  echo " started."

  if [ -f /var/spamtagger/run/commtouch.rn ]; then
    rm /var/spamtagger/run/commtouch.rn
  fi
  rm /var/spamtagger/run/commtouch.stopped >/dev/null 2>&1
  rm /var/spamtagger/run/commtouch.*.rs >/dev/null 2>&1
  ;;
stop)
  touch /var/spamtagger/run/commtouch.stop.rs
  echo "  Stopping Commtouch daemons: "
  echo -n "    Ctasd daemon..."
  $CTASD_STARTER stop >/dev/null
  echo " stopped."
  echo -n "    Ctipd daemon..."
  $CTIPD_STARTER stop >/dev/null
  echo " stopped."

  sleep 5
  killall -q -KILL ctasd.bin
  killall -q -KILL ctipd.bin

  touch /var/spamtagger/run/commtouch.stopped
  rm /var/spamtagger/run/commtouch.stop.rs >/dev/null 2>&1
  ;;
restart | reload | force-reload)
  touch /var/spamtagger/run/commtouch.restart.rs
  $0 stop
  sleep 3
  $0 start
  ;;
*)
  echo "Usage: /etc/init.d/commtouch {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
