#!/bin/sh
#/etc/init.d/kaspersky: start Kaspersky daemon.

export PATH=$PATH:/sbin:/usr/sbin

KASPERSKYDIR=/opt/kaspersky/bin

# Exit if the package is not installed
[ ! -e "${KASPERSKYDIR}/kavehost.sh" ] && exit 0

DAEMON='./kavehost.sh'
KASPERSKYDOPTS=" -c /opt/kaspersky/bin/kavehost.xml"

prepare() {
  /opt/spamtagger/bin/dump_mailscanner_config.pl >/dev/null 2>&1
}

chown -R spamtagger:spamtagger /var/spamtagger/log/kaspersky

case "$1" in
start)
  touch /var/spamtagger/run/kaspersky.start.rs
  echo -n "  Starting Kaspersky daemon: "
  prepare
  # We need to run Kaspersky from the kaspersky directory
  CURRDIR=$(pwd)
  cd $KASPERSKYDIR
  $DAEMON $KASPERSKYDOPTS >/dev/null 2>&1
  cd $CURRDIR
  echo "started."
  if [ -f /var/spamtagger/run/kaspersky.rn ]; then
    rm /var/spamtagger/run/kaspersky.rn
  fi
  rm /var/spamtagger/run/kaspersky.stopped >/dev/null 2>&1
  rm /var/spamtagger/run/kaspersky.*.rs >/dev/null 2>&1
  ;;
stop)
  touch /var/spamtagger/run/kaspersky.stop.rs
  echo -n "  Stopping Kaspersky daemon: "
  kasperskyPID=$(pgrep -f kavehost.xml)
  if [ ! "$kasperskyPID" = "" ]; then
    kill -KILL $kasperskyPID >/dev/null 2>&1
    sleep 3
  fi
  kasperskyPID=$(pgrep -f kavscanner)
  if [ ! "$kasperskyPID" = "" ]; then
    kill -KILL $kasperskyPID >/dev/null 2>&1
    sleep 3
  fi
  echo "stopped."
  touch /var/spamtagger/run/kaspersky.stopped
  rm /var/spamtagger/run/kaspersky.stop.rs >/dev/null 2>&1
  ;;
restart)
  touch /var/spamtagger/run/kaspersky.restart.rs
  $0 stop
  sleep 1
  $0 start
  ;;
*)
  echo "Usage: /etc/init.d/kaspersky {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
