#!/usr/bin/env sh

usage () {
  echo "usage: $0 [start|stop|restart|status]"
  exit
}

if [ -z $1 ]; then
  usage
fi

if [ $1 = 'start' ]; then
  systemctl start spamtagger.target
elif [ $1 = 'stop' ]; then
  systemctl start spamtagger-stopped.target
elif [ $1 = 'restart' ]; then
  $0 stop
  $0 start
elif [ $1 = 'status' ]; then
  /usr/spamtagger/bin/get_status.pl -s -v
else
  usage
fi
