#!/usr/bin/env perl
#
#   SpamTagger - Open Source Spam Filtering
#   Copyright (C) 2026 John Mertz <git@john.me.tz>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.

use v5.40;
use strict;
use warnings;
use utf8;

use lib '/usr/spamtagger/lib';
use ManageServices;

our $service = 'ntpd';

my $manager = ManageServices->new( 'autoStart' => 0 ) || die "Failed to create object: $!\n";
$manager->loadModule($service) || die "Could not load module for service: $service\n";

unless (scalar(@ARGV) && defined($manager->{'module'}->{'actions'}->{$ARGV[0]})) {
    print "\nusage: $0 <action>\n\n";
    $manager->usage($service);
    exit();
}

my $action = shift;

my $status = $manager->{'module'}->{'actions'}->{$action}->{'cmd'}($manager);

if (defined($status) ) {
    print $manager->{'services'}->{$service}->{'name'} . ': ';
    if ($status =~ m/^\-?\d$/) {
        print $manager->{'codes'}->{$status}->{'verbose'} . "\n";
    } else {
        print $status . "\n";
    }
} 
