[Unit]
Description=Freshclam virus signature updater for SpamTagger
After=network.target mariadb@replica.service
Requires=mariadb@replica.service
PartOf=spamtagger.target

[Service]
User=clamav
Group=spamtagger
ExecStart=
ExecStart=/usr/bin/freshclam --user=clamav --config-file=/var/spamtagger/etc/clamav/freshclam.conf --daemon-notify=/var/spamtagger/etc/clamav/clamd.conf --log=/var/spamtagger/log/clamav/freshclam.log
ExecStartPre=+/opt/spamtagger/bin/dump_freshclam_config.pl

[Install]
WantedBy=spamtagger.target
